version: '3.7'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=S3cret
      - MYSQL_USER=docker_user
      - MYSQL_DATABASE=solid_api
  app_dev:  
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: solidapi_dev
    network_mode: host
    volumes:
      - .:/usr/dev #WORKDIR

  app_production:  
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: solidapi_prod
    restart: unless-stopped
    ports:
      - 3000:3000
volumes:
  mysql:
    driver: local