version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: solidapi-mysql
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solidapi
  app_dev:  
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: solidapi_dev
    network_mode: host
    volumes:
      - .:/usr/dev #WORKDIR

  app_production:  
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: solidapi_prod
    restart: unless-stopped
    ports:
      - 3000:3000
volumes:
  mysql:
    driver: local