service: aws-node-express-api-project
frameworkVersion: '3'
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: 'sa-east-1'
  vpc:
    securityGroupIds:
      - sg-06b59a382b60067c4
      - sg-0a06b65bdfd465541
      - sg-0a6dff02d5d90f26e
    subnetIds:
      - subnet-0f089c3ab61895ca0
      - subnet-0cb9266d131939448
      - subnet-0c8fdd185d0ed9fa5

custom:
  dotenv:
    path: .env
  esbuild:
    bundle: true
    minify: true
    watch:
      pattern: ['./','src/**/*.ts']
package: 
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - 'node_modules/.prisma/client/libquery_engine-debian-*'

    - '!node_modules/prisma/libquery_engine-*'
    - 'node_modules/.prisma/client/schema.prisma'
  
functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
